### ISSUE TITLE
Non deterministic behavior of test_findprev_asymptote

### ISSUE THREAD

**Issue by Tockra** [JMurph2015/rust-vebtrees#2]
Hello,

sometimes your following test fails with (cargo test) not always but 1 of 15 executions.

```bash
running 1 test
test test_asymptotes::test_findprev_asymptote ... FAILED

failures:

---- test_asymptotes::test_findprev_asymptote stdout ----
sum_x: 125250000.0, sum_y=NaN, sum_xy=NaN, sum_x_2=41791750000000.0, sum_y_2=NaN
Numerator: NaN, Denominator: NaN
corr: NaN
thread 'test_asymptotes::test_findprev_asymptote' panicked at 'assertion failed: corr > 0.70', src\test_asymptotes.rs:134:5
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.29\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libstd\sys_common\backtrace.rs:47
   2: std::sys_common::backtrace::print
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libstd\sys_common\backtrace.rs:36
   3: std::panicking::default_hook::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libstd\panicking.rs:200
   4: std::panicking::default_hook
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libstd\panicking.rs:211
   5: std::panicking::rust_panic_with_hook
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libstd\panicking.rs:477
   6: std::panicking::begin_panic<str*>
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\libstd\panicking.rs:411
   7: vebtrees::test_asymptotes::test_findprev_asymptote
             at .\src\test_asymptotes.rs:134
   8: vebtrees::test_asymptotes::test_findprev_asymptote::{{closure}}
             at .\src\test_asymptotes.rs:105
   9: core::ops::function::FnOnce::call_once<closure,()>
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\libcore\ops\function.rs:231
  10: alloc::boxed::{{impl}}::call_once<(),FnOnce<()>>
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\liballoc\boxed.rs:746
  11: panic_unwind::__rust_maybe_catch_panic
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libpanic_unwind\lib.rs:82
  12: std::panicking::try
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\libstd\panicking.rs:275
  13: std::panic::catch_unwind
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\libstd\panic.rs:394
  14: test::run_test::run_test_inner::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libtest\lib.rs:1466
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    test_asymptotes::test_findprev_asymptote

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 11 filtered out
```

I dont see the reason. Maybe you do.

T

**Comment by Tockra** [comment]
Okay I see many different tests fails

**Comment by JMurph2015** [comment]
Yeah, so some of the tests are actually more like benchmarks.  They attempt to verify the O(loglog(n)) behavior of the structure.  However, this is error prone because there is noise in how long a particular execution takes.  I might move these to be proper benchmarks, or perhaps come up with some better way to assure the asymptotic bound.
